"""Defines local PyPI-based repositories. Their deps
should be installed later in WORKSPACE file to be accessible.
`pip_parse` takes a `requirements_lock` file as input, which is
generated by the `bazel run :requirements.update` command."""

def pypi_repos():
    pass
    #pyprotoc_plugin_pypi_repos()
